# Generated by Django 5.1 on 2024-09-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_alter_organizador_email_alter_organizador_telefono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizador",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="telefono",
            field=models.CharField(default="000-000-0000", max_length=15),
        ),
    ]
