# Generated by Django 5.1 on 2024-09-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0003_alter_organizador_email_alter_organizador_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="evento",
            name="organizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="eventos.organizador"
            ),
        ),
        migrations.AlterField(
            model_name="organizador",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
